### ISSUE TITLE
Those logs of otel-collector was always [severity: "ERROR"]

### ISSUE THREAD

**Issue by philipz** [GoogleCloudPlatform/opentelemetry-operations-collector#186]
I used the below config to deploy OpenTelemetryCollector CRD.  But, I checked the logs of otel-collector  in GKE workloads page, then logs' severity was "ERROR", like the printscreen png.

Would I miss any config of OpenTelemetryCollector CRD ? Thank you.
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  image: otel/opentelemetry-collector-contrib:latest
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 65
        spike_limit_percentage: 20

    exporters:
      googlecloud:
      logging:
        loglevel: debug

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter]
          exporters: [logging, googlecloud]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter]
          exporters: [googlecloud]
        logs:
          receivers: [otlp]
          processors: [memory_limiter]
          exporters: [googlecloud]
```

![otel-col-errorlog](https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/assets/664465/14d4ae30-9cdc-4d23-b57e-19864545bb52)
