### ISSUE TITLE
Consider separating environment variables

### ISSUE THREAD

**Issue by james-bebbington** [GoogleCloudPlatform/opentelemetry-operations-collector#25]
Viper does not support "includes", but it does support loading from and merging multiple config files (with the caveat that arrays are not merged). This means we could change the startup code to load all *.yaml files in the same directory as the executable (or based on some provided regex flag) and change the config to be logically separated, e.g.:

```yaml
<config.yaml>
# shared components listed here
```
```yaml
<config_self.yaml>
pipelines:
  metrics/self:
    receivers: [ prometheus/self ]
    processors: [ metricstransformprocessor/self ]
    exporters: [ ... ]

receivers:
  prometheus/self:
    # scrape self metrics

processors:
  metricstransformprocessor/self:
    ...
```
```yaml
<config_iis.yaml>
pipelines:
  metrics/iis:
    receivers: [ windowsperformancecountersreceiver/iis ]
    processors: [ metricstransformprocessor/iis ]
    exporters: [ ... ]

receivers:
  windowsperformancecountersreceiver/iis:
    ...

processors:
  metricstransformprocessor/iis:
    ...
```
```yaml
<config_sqlserver.yaml>
pipelines:
  metrics/sqlserver:
    receivers: [ windowsperformancecountersreceiver/sqlserver ]
    processors: [ metricstransformprocessor/sqlserver ]
    exporters: [ ... ]

receivers:
  windowsperformancecountersreceiver/sqlserver:
    ...

processors:
  metricstransformprocessor/sqlserver:
    ...
```

In addition, we could support loading constants into environment variables to avoid constants having to be repeated across all files, e.g.:

```yaml
<config_env.yaml>
USERAGENT: Google Cloud Metrics Agent/{{version}} (TargetPlatform=windows; Framework=OpenTelemetry Collector)
```

```yaml
<config_*.yaml>
exporters:
  stackdriver/sqlserver:
    user_agent: $USERAGENT
```
