### ISSUE TITLE
Consider using less commonly used port(s)

### ISSUE THREAD

**Issue by ravwojdyla** [GoogleCloudPlatform/opentelemetry-operations-collector#86]
After installing https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent via GCP instructions:

![image](https://user-images.githubusercontent.com/1419010/159916201-b55a0086-c14d-4581-838f-c37a52af692e.png)

We have encountered a couple of issues:
 * first the agent did not work at all
 * after restart of the VM, it started working BUT broke Jupyter Lab installation

Turns out one of the services (`prometheus/otel`?) uses port 8888, which is arguable a commonly used port. Right after the installation that port was taken by Jupyter Lab, thus the agents did not fully work, then after the reboot, the port was taken by the agent and our Jupyter Lab installation broke because Jupyter Lab could no longer use port 8888.

The process using the port 8888:

>  /opt/google-cloud-ops-agent/subagents/opentelemetry-collector/otelopscol --config=/run/google-cloud-ops-agent-opentelemetry-collector/otel.yaml

In the config I can see:

```yaml
  prometheus/otel:
    config:
      scrape_configs:
      - job_name: otel-collector
        scrape_interval: 1m
        static_configs:
        - targets:
          - 0.0.0.0:8888
```

Would it be possible to use less commonly used port for a process that should arguable be "invisible" to the users please?
